// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwnH3IMtGBfKScrv9EoizeZ8rFlb7Wm0',
    appId: '1:172807214156:web:9cd3e43ce2ecab6b7b50e9',
    messagingSenderId: '172807214156',
    projectId: 'moodtracker-e0978',
    authDomain: 'moodtracker-e0978.firebaseapp.com',
    storageBucket: 'moodtracker-e0978.appspot.com',
    measurementId: 'G-F57M9RTM3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVaKGT-UlOFeWPZIaqYJIQFxqXr5rs0l0',
    appId: '1:172807214156:android:743abdbee009720c7b50e9',
    messagingSenderId: '172807214156',
    projectId: 'moodtracker-e0978',
    storageBucket: 'moodtracker-e0978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGUKo8MmP5TijD4fmWXUWMylIFfAnyHlA',
    appId: '1:172807214156:ios:d89ce01a36c183ea7b50e9',
    messagingSenderId: '172807214156',
    projectId: 'moodtracker-e0978',
    storageBucket: 'moodtracker-e0978.appspot.com',
    iosClientId: '172807214156-kfrrpibi51sj8gtrqcvan8r6t9a1fmel.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGUKo8MmP5TijD4fmWXUWMylIFfAnyHlA',
    appId: '1:172807214156:ios:d89ce01a36c183ea7b50e9',
    messagingSenderId: '172807214156',
    projectId: 'moodtracker-e0978',
    storageBucket: 'moodtracker-e0978.appspot.com',
    iosClientId: '172807214156-kfrrpibi51sj8gtrqcvan8r6t9a1fmel.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodtracker',
  );
}
